# Exercise 1

### Imports and reading data

In [1028]:
import pandas as pd
import numpy as np
path = "..\\..\\Lecture Code (my notes)\\Assets\\Data\\"

# Read in dataframe
df = pd.read_csv(path+"imdb_top_1000.csv")

### Task 1: Get rid of useless columns

In [1029]:
# Drop the unecessary columns. We won't be using these.
df.drop(columns=["Poster_Link","Certificate","Overview","Runtime","Meta_score","No_of_Votes"], inplace=True)
df.head()

,Series_Title,Released_Year,Genre,IMDB_Rating,Director,Star1,Star2,Star3,Star4,Gross
0,The Shawshank Redemption,1994,Drama,9.3,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,"28,341,469"
1,The Godfather,1972,"Crime, Drama",9.2,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,"134,966,411"
2,The Dark Knight,2008,"Action, Crime, Drama",9.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,"534,858,444"
3,The Godfather: Part II,1974,"Crime, Drama",9.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,"57,300,000"
4,12 Angry Men,1957,"Crime, Drama",9.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,"4,360,000"

### Intermission Task: Analyze and Clean Data

In [1030]:
# Next, we should do an analysis of the data and clean it if possible.
# We'll take a look at various statistics.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Series_Title   1000 non-null   object
 1   Released_Year  1000 non-null   object
 2   Genre          1000 non-null   object
 3   IMDB_Rating    1000 non-null   float64
 4   Director       1000 non-null   object
 5   Star1          1000 non-null   object
 6   Star2          1000 non-null   object
 7   Star3          1000 non-null   object
 8   Star4          1000 non-null   object
 9   Gross          831 non-null    object
dtypes: float64(1), object(9)
memory usage: 78.3+ KB

In [1031]:
df.head()

,Series_Title,Released_Year,Genre,IMDB_Rating,Director,Star1,Star2,Star3,Star4,Gross
0,The Shawshank Redemption,1994,Drama,9.3,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,"28,341,469"
1,The Godfather,1972,"Crime, Drama",9.2,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,"134,966,411"
2,The Dark Knight,2008,"Action, Crime, Drama",9.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,"534,858,444"
3,The Godfather: Part II,1974,"Crime, Drama",9.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,"57,300,000"
4,12 Angry Men,1957,"Crime, Drama",9.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,"4,360,000"

In [1032]:
# Things of note:
# 1. Gross has 169 null entries. These will need to be filled.
#
# 2. Gross should also not be an object- we should also expect this to be an integer.
# This is likely because of the commas included in the numbers (4,360,000 for example), making them strings.
#
# 3. The release year should ideally not be an object- we should expect an integer here.
#
# Let's investigate each of these.

In [1033]:
# 1. Gross has null entries

# We could simply fill these with averages- but this will mess with out values when we do aggregates later.
# It would be best to simply delete these entries.
df = df.dropna()
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 831 entries, 0 to 997
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Series_Title   831 non-null    object
 1   Released_Year  831 non-null    object
 2   Genre          831 non-null    object
 3   IMDB_Rating    831 non-null    float64
 4   Director       831 non-null    object
 5   Star1          831 non-null    object
 6   Star2          831 non-null    object
 7   Star3          831 non-null    object
 8   Star4          831 non-null    object
 9   Gross          831 non-null    object
dtypes: float64(1), object(9)
memory usage: 71.4+ KB

In [1034]:
# The 169 null entries have been deleted- we are left with 831

# 2. Gross should be an integer

# We must remove the commas before converting, as they will cause an error in the cast.
df["Gross"] = df["Gross"].str.replace(',','').astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 831 entries, 0 to 997
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Series_Title   831 non-null    object
 1   Released_Year  831 non-null    object
 2   Genre          831 non-null    object
 3   IMDB_Rating    831 non-null    float64
 4   Director       831 non-null    object
 5   Star1          831 non-null    object
 6   Star2          831 non-null    object
 7   Star3          831 non-null    object
 8   Star4          831 non-null    object
 9   Gross          831 non-null    int64
dtypes: float64(1), int64(1), object(8)
memory usage: 71.4+ KB

In [1035]:
# Gross is now an int64 type!

# 3. Release year should be an integer. 

# Let's investigate its range of values.
df["Released_Year"].value_counts()

Released_Year
2014    31
2004    29
2013    27
2009    25
2007    25
        ..
1947     1
1938     1
1933     1
PG       1
1953     1
Name: count, Length: 95, dtype: int64

In [1036]:
# The 'PG' entry should not be there. We'll keep only entries with numerical characters
df = df[df["Released_Year"].str.contains(r"[0-9]+")]
df["Released_Year"] = df["Released_Year"].astype(int)

df["Released_Year"].value_counts()

Released_Year
2014    31
2004    29
2013    27
2007    25
2009    25
        ..
1956     1
1945     1
1938     1
1933     1
1953     1
Name: count, Length: 94, dtype: int64

In [1037]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 830 entries, 0 to 997
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Series_Title   830 non-null    object
 1   Released_Year  830 non-null    int64
 2   Genre          830 non-null    object
 3   IMDB_Rating    830 non-null    float64
 4   Director       830 non-null    object
 5   Star1          830 non-null    object
 6   Star2          830 non-null    object
 7   Star3          830 non-null    object
 8   Star4          830 non-null    object
 9   Gross          830 non-null    int64
dtypes: float64(1), int64(2), object(7)
memory usage: 71.3+ KB

In [1038]:
# We were able to remove the PG entry. Looks like it was the only one that needed removing.

### Task 2: Oldest Movie

In [1039]:
# Find the oldest movie
df.loc[df["Released_Year"] == df["Released_Year"].min()]

# Alternatively:
# df.nsmallest(1, columns=["Released_Year"])

,Series_Title,Released_Year,Genre,IMDB_Rating,Director,Star1,Star2,Star3,Star4,Gross
127,The Kid,1921,"Comedy, Drama, Family",8.3,Charles Chaplin,Charles Chaplin,Edna Purviance,Jackie Coogan,Carl Miller,5450000

### Task 3: Newest Movie

In [1040]:
# Find the newest movie
df.loc[df["Released_Year"] == df["Released_Year"].max()]

# This has multiple movies "tied" for first place, since only the year is listed.
# This could be used instead if you only wanted one:
# df.nlargest(1, columns=["Released_Year"])

,Series_Title,Released_Year,Genre,IMDB_Rating,Director,Star1,Star2,Star3,Star4,Gross
19,Gisaengchung,2019,"Comedy, Drama, Thriller",8.6,Bong Joon Ho,Kang-ho Song,Lee Sun-kyun,Cho Yeo-jeong,Choi Woo-sik,53367844
33,Joker,2019,"Crime, Drama, Thriller",8.5,Todd Phillips,Joaquin Phoenix,Robert De Niro,Zazie Beetz,Frances Conroy,335451311
59,Avengers: Endgame,2019,"Action, Adventure, Drama",8.4,Anthony Russo,Joe Russo,Robert Downey Jr.,Chris Evans,Mark Ruffalo,858373000
84,1917,2019,"Drama, Thriller, War",8.3,Sam Mendes,Dean-Charles Chapman,George MacKay,Daniel Mays,Colin Firth,159227644
128,Chhichhore,2019,"Comedy, Drama",8.2,Nitesh Tiwari,Sushant Singh Rajput,Shraddha Kapoor,Varun Sharma,Prateik,898575
195,Portrait de la jeune fille en feu,2019,"Drama, Romance",8.1,Céline Sciamma,Noémie Merlant,Adèle Haenel,Luàna Bajrami,Valeria Golino,3759854
217,Ford v Ferrari,2019,"Action, Biography, Drama",8.1,James Mangold,Matt Damon,Christian Bale,Jon Bernthal,Caitriona Balfe,117624028
334,Gully Boy,2019,"Drama, Music, Romance",8.0,Zoya Akhtar,Vijay Varma,Nakul Roshan Sahdev,Ranveer Singh,Vijay Raaz,5566534
463,Knives Out,2019,"Comedy, Crime, Drama",7.9,Rian Johnson,Daniel Craig,Chris Evans,Ana de Armas,Jamie Lee Curtis,165359751
466,Marriage Story,2019,"Comedy, Drama, Romance",7.9,Noah Baumbach,Adam Driver,Scarlett Johansson,Julia Greer,Azhy Robertson,2000000
475,Jojo Rabbit,2019,"Comedy, Drama, War",7.9,Taika Waititi,Roman Griffin Davis,Thomasin McKenzie,Scarlett Johansson,Taika Waititi,349555
484,The Irishman,2019,"Biography, Crime, Drama",7.9,Martin Scorsese,Robert De Niro,Al Pacino,Joe Pesci,Harvey Keitel,7000000
585,Little Women,2019,"Drama, Romance",7.8,Greta Gerwig,Saoirse Ronan,Emma Watson,Florence Pugh,Eliza Scanlen,108101214
596,Toy Story 4,2019,"Animation, Adventure, Comedy",7.8,Josh Cooley,Tom Hanks,Tim Allen,Annie Potts,Tony Hale,434038008
879,Once Upon a Time... in Hollywood,2019,"Comedy, Drama",7.6,Quentin Tarantino,Leonardo DiCaprio,Brad Pitt,Margot Robbie,Emile Hirsch,142502728
884,The Peanut Butter Falcon,2019,"Adventure, Comedy, Drama",7.6,Tyler Nilson,Michael Schwartz,Zack Gottsagen,Ann Owens,Dakota Johnson,13122642

### Task 4: Top 10 movies by IMDB rating

In [1041]:
# Get top 10 movies
df.nlargest(10, columns=["IMDB_Rating"])
# Another option: df.sort_values("IMDB_Rating", ascending=False).head(10)

,Series_Title,Released_Year,Genre,IMDB_Rating,Director,Star1,Star2,Star3,Star4,Gross
0,The Shawshank Redemption,1994,Drama,9.3,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,28341469
1,The Godfather,1972,"Crime, Drama",9.2,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,134966411
2,The Dark Knight,2008,"Action, Crime, Drama",9.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,534858444
3,The Godfather: Part II,1974,"Crime, Drama",9.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,57300000
4,12 Angry Men,1957,"Crime, Drama",9.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,4360000
5,The Lord of the Rings: The Return of the King,2003,"Action, Adventure, Drama",8.9,Peter Jackson,Elijah Wood,Viggo Mortensen,Ian McKellen,Orlando Bloom,377845905
6,Pulp Fiction,1994,"Crime, Drama",8.9,Quentin Tarantino,John Travolta,Uma Thurman,Samuel L. Jackson,Bruce Willis,107928762
7,Schindler's List,1993,"Biography, Drama, History",8.9,Steven Spielberg,Liam Neeson,Ralph Fiennes,Ben Kingsley,Caroline Goodall,96898818
8,Inception,2010,"Action, Adventure, Sci-Fi",8.8,Christopher Nolan,Leonardo DiCaprio,Joseph Gordon-Levitt,Elliot Page,Ken Watanabe,292576195
9,Fight Club,1999,Drama,8.8,David Fincher,Brad Pitt,Edward Norton,Meat Loaf,Zach Grenier,37030102

### Task 5: Top movie for each genre

In [1042]:
# I imagine there are lots of ways to tackle this problem- this is what I came up with.

# The genres are combined
movies = df['Genre'].str.split(', ')

# Creates a list of each unique genre
unique_genres = []
for movie in movies:
    for genre in movie:
        if(genre not in unique_genres):
            unique_genres.append(genre)
unique_genres.sort()

# Find the best in each movie genre
for genre in unique_genres:
    # Get the name of the highest rated movie
    # Maybe this is too dense. It's a nice one-liner though.
    best = df.loc[df["Genre"].str.contains(genre)].nlargest(1, "IMDB_Rating")

    # Print results
    print(f"Best movie in {genre} goes to:\n{best["Series_Title"].values[0]+"\n"}")

Best movie in Action goes to:
The Dark Knight

Best movie in Adventure goes to:
The Lord of the Rings: The Return of the King

Best movie in Animation goes to:
Sen to Chihiro no kamikakushi

Best movie in Biography goes to:
Schindler's List

Best movie in Comedy goes to:
Gisaengchung

Best movie in Crime goes to:
The Godfather

Best movie in Drama goes to:
The Shawshank Redemption

Best movie in Family goes to:
Sen to Chihiro no kamikakushi

Best movie in Fantasy goes to:
Star Wars: Episode V - The Empire Strikes Back

Best movie in Film-Noir goes to:
Double Indemnity

Best movie in History goes to:
Schindler's List

Best movie in Horror goes to:
Psycho

Best movie in Music goes to:
Whiplash

Best movie in Musical goes to:
Singin' in the Rain

Best movie in Mystery goes to:
Se7en

Best movie in Romance goes to:
Forrest Gump

Best movie in Sci-Fi goes to:
Inception

Best movie in Sport goes to:
Bacheha-Ye aseman

Best movie in Thriller goes to:
Gisaengchung

Best movie in War goes to:
Saving Private Ryan

Best movie in Western goes to:
Il buono, il brutto, il cattivo

### Task 6: Director with the most movies

In [1043]:
# Get the value counts for each director. By default the highest will be at the 0th index.
dir_counts = df["Director"].value_counts()
print(f"The director with the most movies is: {dir_counts.keys()[0]}")

The director with the most movies is: Steven Spielberg

### Task 7: Star with the most movies

In [1044]:
# Creates a dataframe of stars and their total movie count for each Star column (Star1/Star2 etc)
stars = pd.concat([df[column].value_counts() for column in df if "Star" in column], axis = 1)
# Sums their count for each Star column
stars = stars.sum(axis=1)

# Print result
print(f"The star that has appeared in the most movies is: {stars.nlargest(1).keys()[0]}")

The star that has appeared in the most movies is: Robert De Niro

### Task 8: Highest grossing movie for each genre

In [1045]:
# We can reuse the unique_genres variable from earlier

# Find the highest grossing movie in each genre
for genre in unique_genres:
    # Get the name of the grossing movie in the genre
    best = df.loc[df["Genre"].str.contains(genre)].nlargest(1, "Gross")

    # Print results
    print(f"Highest grossing movie in {genre} goes to:\n{best["Series_Title"].values[0]+"\n"}")

Highest grossing movie in Action goes to:
Star Wars: Episode VII - The Force Awakens

Highest grossing movie in Adventure goes to:
Star Wars: Episode VII - The Force Awakens

Highest grossing movie in Animation goes to:
Incredibles 2

Highest grossing movie in Biography goes to:
The Blind Side

Highest grossing movie in Comedy goes to:
Toy Story 4

Highest grossing movie in Crime goes to:
The Dark Knight

Highest grossing movie in Drama goes to:
Avengers: Endgame

Highest grossing movie in Family goes to:
E.T. the Extra-Terrestrial

Highest grossing movie in Fantasy goes to:
Avatar

Highest grossing movie in Film-Noir goes to:
Notorious

Highest grossing movie in History goes to:
Gone with the Wind

Highest grossing movie in Horror goes to:
The Exorcist

Highest grossing movie in Music goes to:
Bohemian Rhapsody

Highest grossing movie in Musical goes to:
Fiddler on the Roof

Highest grossing movie in Mystery goes to:
The Sixth Sense

Highest grossing movie in Romance goes to:
Titanic

Highest grossing movie in Sci-Fi goes to:
Star Wars: Episode VII - The Force Awakens

Highest grossing movie in Sport goes to:
The Blind Side

Highest grossing movie in Thriller goes to:
Joker

Highest grossing movie in War goes to:
Saving Private Ryan

Highest grossing movie in Western goes to:
Dances with Wolves

### Task 9: Lowest grossing movie for each director

In [1046]:
# Get all unique directors
directors = df["Director"].unique()

# Find the lowest grossing movie for each director
for director in directors:
    # Find the lowest grossing movie for the current director
    worst = df.loc[df["Director"].str.contains(director)].nsmallest(1, "Gross")

    # Print results
    print(f"{director}'s lowest grossing movie is:\n{worst["Series_Title"].values[0]+"\n"}")

Frank Darabont's lowest grossing movie is:
The Shawshank Redemption

Francis Ford Coppola's lowest grossing movie is:
The Conversation

Christopher Nolan's lowest grossing movie is:
Memento

Sidney Lumet's lowest grossing movie is:
12 Angry Men

Peter Jackson's lowest grossing movie is:
The Hobbit: The Desolation of Smaug

Quentin Tarantino's lowest grossing movie is:
Reservoir Dogs

Steven Spielberg's lowest grossing movie is:
Empire of the Sun

David Fincher's lowest grossing movie is:
Zodiac

Robert Zemeckis's lowest grossing movie is:
Back to the Future Part II

Sergio Leone's lowest grossing movie is:
Giù la testa

Lana Wachowski's lowest grossing movie is:
The Matrix

Martin Scorsese's lowest grossing movie is:
The King of Comedy

Irvin Kershner's lowest grossing movie is:
Star Wars: Episode V - The Empire Strikes Back

Milos Forman's lowest grossing movie is:
Amadeus

Bong Joon Ho's lowest grossing movie is:
Salinui chueok

Fernando Meirelles's lowest grossing movie is:
Cidade de Deus

Hayao Miyazaki's lowest grossing movie is:
Kaze no tani no Naushika

Roberto Benigni's lowest grossing movie is:
La vita è bella

Jonathan Demme's lowest grossing movie is:
Philadelphia

George Lucas's lowest grossing movie is:
Star Wars

Akira Kurosawa's lowest grossing movie is:
Ikiru

Todd Phillips's lowest grossing movie is:
The Hangover

Damien Chazelle's lowest grossing movie is:
Whiplash

Olivier Nakache's lowest grossing movie is:
The Intouchables

Roman Polanski's lowest grossing movie is:
Le locataire

Ridley Scott's lowest grossing movie is:
Blade Runner

Tony Kaye's lowest grossing movie is:
Detachment

Bryan Singer's lowest grossing movie is:
The Usual Suspects

Luc Besson's lowest grossing movie is:
Léon

Roger Allers's lowest grossing movie is:
The Lion King

James Cameron's lowest grossing movie is:
The Terminator

Giuseppe Tornatore's lowest grossing movie is:
La migliore offerta

Alfred Hitchcock's lowest grossing movie is:
Dial M for Murder

Michael Curtiz's lowest grossing movie is:
Casablanca

Charles Chaplin's lowest grossing movie is:
City Lights

Nadine Labaki's lowest grossing movie is:
Capharnaüm

Makoto Shinkai's lowest grossing movie is:
Kimi no na wa.

Nitesh Tiwari's lowest grossing movie is:
Chhichhore

Bob Persichetti's lowest grossing movie is:
Spider-Man: Into the Spider-Verse

Anthony Russo's lowest grossing movie is:
Captain America: The Winter Soldier

Lee Unkrich's lowest grossing movie is:
Coco

Rajkumar Hirani's lowest grossing movie is:
Lage Raho Munna Bhai

Aamir Khan's lowest grossing movie is:
Taare Zameen Par

Andrew Stanton's lowest grossing movie is:
WALL·E

Florian Henckel von Donnersmarck's lowest grossing movie is:
The Lives of Others

Chan-wook Park's lowest grossing movie is:
Boksuneun naui geot

Stanley Kubrick's lowest grossing movie is:
Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb

Billy Wilder's lowest grossing movie is:
Ace in the Hole

Sam Mendes's lowest grossing movie is:
Road to Perdition

Sriram Raghavan's lowest grossing movie is:
Andhadhun

Thomas Vinterberg's lowest grossing movie is:
Jagten

Asghar Farhadi's lowest grossing movie is:
Darbareye Elly

Denis Villeneuve's lowest grossing movie is:
Incendies

Michel Gondry's lowest grossing movie is:
Eternal Sunshine of the Spotless Mind

Jean-Pierre Jeunet's lowest grossing movie is:
Un long dimanche de fiançailles

Guy Ritchie's lowest grossing movie is:
Lock, Stock and Two Smoking Barrels

Darren Aronofsky's lowest grossing movie is:
Requiem for a Dream

Gus Van Sant's lowest grossing movie is:
Good Will Hunting

Majid Majidi's lowest grossing movie is:
Bacheha-Ye aseman

John Lasseter's lowest grossing movie is:
Toy Story

Mel Gibson's lowest grossing movie is:
Apocalypto

Brian De Palma's lowest grossing movie is:
Carlito's Way

Richard Marquand's lowest grossing movie is:
Star Wars: Episode VI - Return of the Jedi

Wolfgang Petersen's lowest grossing movie is:
Das Boot

George Roy Hill's lowest grossing movie is:
Butch Cassidy and the Sundance Kid

David Lean's lowest grossing movie is:
Lawrence of Arabia

Stanley Donen's lowest grossing movie is:
Singin' in the Rain

Vittorio De Sica's lowest grossing movie is:
Ladri di biciclette

Orson Welles's lowest grossing movie is:
Citizen Kane

Fritz Lang's lowest grossing movie is:
M - Eine Stadt sucht einen Mörder

Aditya Dhar's lowest grossing movie is:
Uri: The Surgical Strike

Peter Farrelly's lowest grossing movie is:
Green Book

Martin McDonagh's lowest grossing movie is:
In Bruges

Meghna Gulzar's lowest grossing movie is:
Talvar

S.S. Rajamouli's lowest grossing movie is:
Bãhubali: The Beginning

Nishikant Kamat's lowest grossing movie is:
Drishyam

Vikas Bahl's lowest grossing movie is:
Queen

Zaza Urushadze's lowest grossing movie is:
Mandariinid

Rakeysh Omprakash Mehra's lowest grossing movie is:
Bhaag Milkha Bhaag

Vikramaditya Motwane's lowest grossing movie is:
Udaan

Tigmanshu Dhulia's lowest grossing movie is:
Paan Singh Tomar

Juan José Campanella's lowest grossing movie is:
El secreto de sus ojos

Gavin O'Connor's lowest grossing movie is:
Warrior

Pete Docter's lowest grossing movie is:
Monsters, Inc.

Shimit Amin's lowest grossing movie is:
Chak De! India

Paul Thomas Anderson's lowest grossing movie is:
Magnolia

Guillermo del Toro's lowest grossing movie is:
Pan's Labyrinth

James McTeigue's lowest grossing movie is:
V for Vendetta

Sanjay Leela Bhansali's lowest grossing movie is:
Black

Ashutosh Gowariker's lowest grossing movie is:
Lagaan: Once Upon a Time in India

Oliver Hirschbiegel's lowest grossing movie is:
Das Experiment

Ron Howard's lowest grossing movie is:
Frost/Nixon

Curtis Hanson's lowest grossing movie is:
L.A. Confidential

Michael Mann's lowest grossing movie is:
The Insider

Clint Eastwood's lowest grossing movie is:
Letters from Iwo Jima

Emir Kusturica's lowest grossing movie is:
Underground

John McTiernan's lowest grossing movie is:
Predator

Andrei Tarkovsky's lowest grossing movie is:
Andrei Rublev

Terry Gilliam's lowest grossing movie is:
Monty Python and the Holy Grail

John Sturges's lowest grossing movie is:
The Magnificent Seven

Jules Dassin's lowest grossing movie is:
Du rififi chez les hommes

Joseph L. Mankiewicz's lowest grossing movie is:
All About Eve

John Huston's lowest grossing movie is:
The African Queen

Buster Keaton's lowest grossing movie is:
Sherlock Jr.

Céline Sciamma's lowest grossing movie is:
Portrait de la jeune fille en feu

Aniruddha Roy Chowdhury's lowest grossing movie is:
Pink

Xavier Dolan's lowest grossing movie is:
Mommy

Vishal Bhardwaj's lowest grossing movie is:
Haider

James Mangold's lowest grossing movie is:
3:10 to Yuma

Lenny Abrahamson's lowest grossing movie is:
Room

Damián Szifron's lowest grossing movie is:
Relatos salvajes

Nuri Bilge Ceylan's lowest grossing movie is:
Bir Zamanlar Anadolu'da

Umesh Shukla's lowest grossing movie is:
OMG: Oh My God!

Wes Anderson's lowest grossing movie is:
Rushmore

Anurag Basu's lowest grossing movie is:
Barfi!

Steve McQueen's lowest grossing movie is:
12 Years a Slave

Tom McCarthy's lowest grossing movie is:
The Station Agent

Tomm Moore's lowest grossing movie is:
The Secret of Kells

Sujoy Ghosh's lowest grossing movie is:
Kahaani

Zoya Akhtar's lowest grossing movie is:
Zindagi Na Milegi Dobara

George Miller's lowest grossing movie is:
Mad Max 2

David Yates's lowest grossing movie is:
Harry Potter and the Deathly Hallows: Part 1

Yôjirô Takita's lowest grossing movie is:
Okuribito

Dean DeBlois's lowest grossing movie is:
How to Train Your Dragon 2

Sean Penn's lowest grossing movie is:
Into the Wild

Ethan Coen's lowest grossing movie is:
No Country for Old Men

Terry George's lowest grossing movie is:
Hotel Rwanda

Je-kyu Kang's lowest grossing movie is:
Taegukgi hwinalrimyeo

Richard Linklater's lowest grossing movie is:
Waking Life

Farhan Akhtar's lowest grossing movie is:
Dil Chahta Hai

Alejandro G. Iñárritu's lowest grossing movie is:
Amores perros

M. Night Shyamalan's lowest grossing movie is:
The Sixth Sense

Peter Weir's lowest grossing movie is:
Dead Poets Society

Joel Coen's lowest grossing movie is:
Blood Simple

Kar-Wai Wong's lowest grossing movie is:
Chung Hing sam lam

Danny Boyle's lowest grossing movie is:
Trainspotting

Mathieu Kassovitz's lowest grossing movie is:
La haine

Krzysztof Kieslowski's lowest grossing movie is:
Trois couleurs: Bleu

Jim Sheridan's lowest grossing movie is:
My Left Foot: The Story of Christy Brown

Kaige Chen's lowest grossing movie is:
Ba wang bie ji

Yimou Zhang's lowest grossing movie is:
Dà hóng denglong gaogao guà

Rob Reiner's lowest grossing movie is:
This Is Spinal Tap

Oliver Stone's lowest grossing movie is:
JFK

Wim Wenders's lowest grossing movie is:
Paris, Texas

John Carpenter's lowest grossing movie is:
The Thing

Alan Parker's lowest grossing movie is:
Pink Floyd: The Wall

Ingmar Bergman's lowest grossing movie is:
Jungfrukällan

Terry Jones's lowest grossing movie is:
Life of Brian

Michael Cimino's lowest grossing movie is:
The Deer Hunter

John G. Avildsen's lowest grossing movie is:
Rocky

Peter Bogdanovich's lowest grossing movie is:
The Last Picture Show

Jean-Pierre Melville's lowest grossing movie is:
Le samouraï

Stuart Rosenberg's lowest grossing movie is:
Cool Hand Luke

Gillo Pontecorvo's lowest grossing movie is:
La battaglia di Algeri

Robert Aldrich's lowest grossing movie is:
What Ever Happened to Baby Jane?

William Wyler's lowest grossing movie is:
The Best Years of Our Lives

Federico Fellini's lowest grossing movie is:
8½

Elia Kazan's lowest grossing movie is:
A Streetcar Named Desire

Carol Reed's lowest grossing movie is:
The Third Man

Michael Powell's lowest grossing movie is:
Peeping Tom

Ernst Lubitsch's lowest grossing movie is:
The Shop Around the Corner

Frank Capra's lowest grossing movie is:
It Happened One Night

Victor Fleming's lowest grossing movie is:
The Wizard of Oz

Jean Renoir's lowest grossing movie is:
La Grande Illusion

Carl Theodor Dreyer's lowest grossing movie is:
La passion de Jeanne d'Arc

F.W. Murnau's lowest grossing movie is:
Sunrise: A Song of Two Humans

Clyde Bruckman's lowest grossing movie is:
The General

Kabir Khan's lowest grossing movie is:
Bajrangi Bhaijaan

Garth Davis's lowest grossing movie is:
Lion

Byron Howard's lowest grossing movie is:
Zootopia

Isao Takahata's lowest grossing movie is:
Omohide poro poro

Stephen Chbosky's lowest grossing movie is:
The Perks of Being a Wallflower

Neeraj Pandey's lowest grossing movie is:
Special Chabbis

Destin Daniel Cretton's lowest grossing movie is:
Short Term 12

Gareth Evans's lowest grossing movie is:
Serbuan maut 2: Berandal

Morten Tyldum's lowest grossing movie is:
The Imitation Game

James Gunn's lowest grossing movie is:
Guardians of the Galaxy

Spike Jonze's lowest grossing movie is:
Adaptation.

José Padilha's lowest grossing movie is:
Tropa de Elite

Tom Hooper's lowest grossing movie is:
The King's Speech

Tate Taylor's lowest grossing movie is:
The Help

Tim Miller's lowest grossing movie is:
Deadpool

Anurag Kashyap's lowest grossing movie is:
Dev.D

Karan Johar's lowest grossing movie is:
My Name Is Khan

Joss Whedon's lowest grossing movie is:
Serenity

Vincent Paronnaud's lowest grossing movie is:
Persepolis

Jean-Marc Vallée's lowest grossing movie is:
Dallas Buyers Club

Gabriele Muccino's lowest grossing movie is:
Seven Pounds

Edward Zwick's lowest grossing movie is:
Glory

Paul Greengrass's lowest grossing movie is:
Captain Phillips

Ki-duk Kim's lowest grossing movie is:
Bin-jip

Frank Miller's lowest grossing movie is:
Sin City

Julian Schnabel's lowest grossing movie is:
Le scaphandre et le papillon

Brad Bird's lowest grossing movie is:
The Iron Giant

Martin Campbell's lowest grossing movie is:
Casino Royale

Andrey Zvyagintsev's lowest grossing movie is:
Vozvrashchenie

Alejandro Amenábar's lowest grossing movie is:
Abre los ojos

Nikkhil Advani's lowest grossing movie is:
Kal Ho Naa Ho

Andrew Lau's lowest grossing movie is:
Mou gaan dou

Gore Verbinski's lowest grossing movie is:
Pirates of the Caribbean: The Curse of the Black Pearl

Tim Burton's lowest grossing movie is:
Ed Wood

Lars von Trier's lowest grossing movie is:
Dogville

Richard Kelly's lowest grossing movie is:
Donnie Darko

David Lynch's lowest grossing movie is:
Lost Highway

Satoshi Kon's lowest grossing movie is:
Tôkyô goddofâzâzu

Walter Salles's lowest grossing movie is:
Central do Brasil

Thomas Jahn's lowest grossing movie is:
Knockin' on Heaven's Door

Billy Bob Thornton's lowest grossing movie is:
Sling Blade

Mike Leigh's lowest grossing movie is:
Naked

Mamoru Oshii's lowest grossing movie is:
Kôkaku Kidôtai

Henry Selick's lowest grossing movie is:
The Nightmare Before Christmas

Harold Ramis's lowest grossing movie is:
Groundhog Day

Taylor Hackford's lowest grossing movie is:
Bound by Honor

Martin Brest's lowest grossing movie is:
Scent of a Woman

Ron Clements's lowest grossing movie is:
The Little Mermaid

Gary Trousdale's lowest grossing movie is:
Beauty and the Beast

Kevin Costner's lowest grossing movie is:
Dances with Wolves

Spike Lee's lowest grossing movie is:
25th Hour

Barry Levinson's lowest grossing movie is:
Sleepers

Katsuhiro Ôtomo's lowest grossing movie is:
Akira

Louis Malle's lowest grossing movie is:
Au revoir les enfants

Richard Attenborough's lowest grossing movie is:
Gandhi

Hal Ashby's lowest grossing movie is:
Being There

Woody Allen's lowest grossing movie is:
The Purple Rose of Cairo

Mel Brooks's lowest grossing movie is:
Young Frankenstein

Franklin J. Schaffner's lowest grossing movie is:
Planet of the Apes

William Friedkin's lowest grossing movie is:
The French Connection

Norman Jewison's lowest grossing movie is:
In the Heat of the Night

Bernardo Bertolucci's lowest grossing movie is:
Il conformista

Mike Nichols's lowest grossing movie is:
The Graduate

Robert Wise's lowest grossing movie is:
The Sound of Music

Robert Rossen's lowest grossing movie is:
The Hustler

Howard Hawks's lowest grossing movie is:
His Girl Friday

Otto Preminger's lowest grossing movie is:
Laura

Richard Brooks's lowest grossing movie is:
Cat on a Hot Tin Roof

Charles Laughton's lowest grossing movie is:
The Night of the Hunter

John Ford's lowest grossing movie is:
The Grapes of Wrath

Lewis Milestone's lowest grossing movie is:
All Quiet on the Western Front

Sergei M. Eisenstein's lowest grossing movie is:
Bronenosets Potemkin

Rian Johnson's lowest grossing movie is:
Knives Out

Hirokazu Koreeda's lowest grossing movie is:
Manbiki kazoku

Noah Baumbach's lowest grossing movie is:
Marriage Story

Luca Guadagnino's lowest grossing movie is:
Call Me by Your Name

Ken Loach's lowest grossing movie is:
I, Daniel Blake

Taika Waititi's lowest grossing movie is:
Jojo Rabbit

Matt Ross's lowest grossing movie is:
Captain Fantastic

John Carney's lowest grossing movie is:
Sing Street

Dan Gilroy's lowest grossing movie is:
Nightcrawler

J.J. Abrams's lowest grossing movie is:
Star Trek Into Darkness

Michel Hazanavicius's lowest grossing movie is:
The Artist

Doug Liman's lowest grossing movie is:
Edge of Tomorrow

Michael Haneke's lowest grossing movie is:
Das weiße Band - Eine deutsche Kindergeschichte

Jacques Audiard's lowest grossing movie is:
Un prophète

Duncan Jones's lowest grossing movie is:
Moon

Tomas Alfredson's lowest grossing movie is:
Låt den rätte komma in

Neill Blomkamp's lowest grossing movie is:
District 9

Imtiaz Ali's lowest grossing movie is:
Jab We Met

Cristian Mungiu's lowest grossing movie is:
4 luni, 3 saptamâni si 2 zile

Tarsem Singh's lowest grossing movie is:
The Fall

Ang Lee's lowest grossing movie is:
Sense and Sensibility

Christophe Barratier's lowest grossing movie is:
Les choristes

Jon Favreau's lowest grossing movie is:
Iron Man

Edgar Wright's lowest grossing movie is:
Shaun of the Dead

Alfonso Cuarón's lowest grossing movie is:
A Little Princess

Pedro Almodóvar's lowest grossing movie is:
La piel que habito

Danis Tanovic's lowest grossing movie is:
No Man's Land

Shin'ichirô Watanabe's lowest grossing movie is:
Cowboy Bebop: Tengoku no tobira

Fabián Bielinsky's lowest grossing movie is:
Nueve reinas

Cameron Crowe's lowest grossing movie is:
Almost Famous

Lee Tamahori's lowest grossing movie is:
Once Were Warriors

Tony Scott's lowest grossing movie is:
True Romance

Bob Clark's lowest grossing movie is:
A Christmas Story

John Landis's lowest grossing movie is:
The Blues Brothers

Bob Fosse's lowest grossing movie is:
All That Jazz

George A. Romero's lowest grossing movie is:
Night of the Living Dead

Alan J. Pakula's lowest grossing movie is:
All the President's Men

Alejandro Jodorowsky's lowest grossing movie is:
La montaña sagrada

Luis Buñuel's lowest grossing movie is:
Belle de jour

Sam Peckinpah's lowest grossing movie is:
The Wild Bunch

Anthony Harvey's lowest grossing movie is:
The Lion in Winter

Alain Resnais's lowest grossing movie is:
Hiroshima mon amour

Cecil B. DeMille's lowest grossing movie is:
The Ten Commandments

Fred Zinnemann's lowest grossing movie is:
High Noon

George Seaton's lowest grossing movie is:
Miracle on 34th Street

Sam Wood's lowest grossing movie is:
A Night at the Opera

Merian C. Cooper's lowest grossing movie is:
King Kong

Theodore Melfi's lowest grossing movie is:
Hidden Figures

Paul King's lowest grossing movie is:
Paddington 2

Travis Knight's lowest grossing movie is:
Kubo and the Two Strings

Kenneth Lonergan's lowest grossing movie is:
Manchester by the Sea

Martin Zandvliet's lowest grossing movie is:
Under sandet

Gareth Edwards's lowest grossing movie is:
Rogue One

Greta Gerwig's lowest grossing movie is:
Little Women

Dorota Kobiela's lowest grossing movie is:
Loving Vincent

Paolo Sorrentino's lowest grossing movie is:
La grande bellezza

Ritesh Batra's lowest grossing movie is:
The Lunchbox

Shoojit Sircar's lowest grossing movie is:
Vicky Donor

Don Hall's lowest grossing movie is:
Big Hero 6

Richard Curtis's lowest grossing movie is:
About Time

Gauri Shinde's lowest grossing movie is:
English Vinglish

Josh Cooley's lowest grossing movie is:
Toy Story 4

Adam McKay's lowest grossing movie is:
The Big Short

Jee-woon Kim's lowest grossing movie is:
Ang-ma-reul bo-at-da

Jeong-beom Lee's lowest grossing movie is:
Ajeossi

F. Gary Gray's lowest grossing movie is:
Straight Outta Compton

Niels Arden Oplev's lowest grossing movie is:
Män som hatar kvinnor

David O. Russell's lowest grossing movie is:
The Fighter

Pierre Morel's lowest grossing movie is:
Taken

Mark Herman's lowest grossing movie is:
The Boy in the Striped Pyjamas

Fatih Akin's lowest grossing movie is:
Auf der anderen Seite

Joe Wright's lowest grossing movie is:
Pride & Prejudice

Nicolas Winding Refn's lowest grossing movie is:
Drive

Jaco Van Dormael's lowest grossing movie is:
Mr. Nobody

Jonathan Dayton's lowest grossing movie is:
Little Miss Sunshine

Yash Chopra's lowest grossing movie is:
Veer-Zaara

Anders Thomas Jensen's lowest grossing movie is:
Adams æbler

Roger Donaldson's lowest grossing movie is:
The World's Fastest Indian

Mikael Håfström's lowest grossing movie is:
Ondskan

Nick Cassavetes's lowest grossing movie is:
The Notebook

Lukas Moodysson's lowest grossing movie is:
Lilja 4-ever

Sylvain Chomet's lowest grossing movie is:
Les triplettes de Belleville

Kevin Reynolds's lowest grossing movie is:
The Count of Monte Cristo

Boaz Yakin's lowest grossing movie is:
Remember the Titans

Troy Duffy's lowest grossing movie is:
The Boondock Saints

Joe Johnston's lowest grossing movie is:
October Sky

Andrew Adamson's lowest grossing movie is:
Shrek

Takeshi Kitano's lowest grossing movie is:
Hana-bi

Andrew Niccol's lowest grossing movie is:
Gattaca

Lasse Hallström's lowest grossing movie is:
What's Eating Gilbert Grape

George P. Cosmatos's lowest grossing movie is:
Tombstone


### Task 10: Save the dataframe as a parquet file

In [1047]:
# This line did not work- not sure if I need to install another library for it or not.
df.to_parquet(path+"imdb_processed")

ImportError: Unable to find a usable engine; tried using: 'pyarrow', 'fastparquet'.
A suitable version of pyarrow or fastparquet is required for parquet support.
Trying to import the above resulted in these errors:
 - Missing optional dependency 'pyarrow'. pyarrow is required for parquet support. Use pip or conda to install pyarrow.
 - Missing optional dependency 'fastparquet'. fastparquet is required for parquet support. Use pip or conda to install fastparquet.

### Task 11: Aggregate the gross revenue for all 1000 movies.

In [ ]:
# There will be 830 movies in mine since I removed movies with no gross revenue
type_stats = df.groupby("IMDB_Rating").agg({"Gross":['mean', 'median']})
type_stats.sort_values(('Gross','mean'), ascending=False)

                    Gross
                     mean       median
IMDB_Rating
9.0          1.988395e+08   57300000.0
8.8          1.963006e+08  292576195.0
8.9          1.942245e+08  107928762.0
8.7          1.926686e+08  171479930.0
9.2          1.349664e+08  134966411.0
8.4          1.337609e+08   25544867.0
8.6          1.112569e+08  100125643.0
8.5          8.977875e+07   23341568.0
7.8          7.568471e+07   32449205.5
8.0          7.131199e+07   24475416.0
7.6          6.914405e+07   39251790.0
7.7          5.884994e+07   27815753.5
8.1          5.249203e+07    5820649.0
7.9          5.240502e+07   12281500.0
8.3          4.758775e+07   15000000.0
8.2          4.553786e+07    5014000.0
9.3          2.834147e+07   28341469.0

# Challenge 1

### Will attempt if I have time after making my QA presentation